### ISSUE TITLE
[Question] validation cross entropy

### ISSUE THREAD

**Issue by YassineYousfi** [commaai/comma10k#2000]
Is the 0.051 validation cross entropy up to date? Are there any FLOPs constraints?

**Comment by geohot** [comment]
Yes, and that was with a unet. But if you can do a lot better with more FLOPS, go for it!

**Comment by YassineYousfi** [comment]
Thanks! 
I used a unet structure too with efficientnet-B4 as encoder, no zooming or TTA. Getting val CE = 0.045.
I can probably do better with weather/lighting augmentations.
I trained first on (H//2, W//2) then continued on full res. Training on full res from scratch gives me around 0.05x too.
Great dataset! I can't wait for the full release.

**Comment by geohot** [comment]
Sweet! Want to open source it?

**Comment by dorkmo** [comment]
is this it? https://github.com/YassineYousfi/comma10k-baseline

**Comment by YassineYousfi** [comment]
Yes @dorkmo, @geohot I will work on it a bit more this weekend and release the weights too.

**Comment by dorkmo** [comment]
very cool! ill share with the #comma-pencil guys on discord

**Comment by geohot** [comment]
Great stuff! Can you add a LICENSE and release weights?

And I didn't know about "segmentation_models.pytorch" or "albumentations", pytorch is fire!

**Comment by geohot** [comment]
It's crazy that this doesn't overfit, you aren't scale augmenting I don't see.

**Comment by YassineYousfi** [comment]
The pytorch ecosystem is 🔥
Sure, I will release weights and a new version ASAP. (I'm slowed down by a conference I'm attending this week)
Thanks for linking to the repo!! I added a MIT license.

**Comment by YassineYousfi** [comment]
There is some regularization (weight_decay), but I would guess that the robustness to overfitting mostly comes from Imagenet pre-trained encoder and the augmentations.

**Comment by YassineYousfi** [comment]
I released the weights here: https://github.com/YassineYousfi/comma10k-baseline/releases/tag/v0.1-alpha
