### ISSUE TITLE
verify mask size in CI job

### ISSUE THREAD

**Issue by gregjhogan** [commaai/comma10k#227]
sometimes people accidentally crop the image
https://github.com/commaai/comma10k/pull/199/files#diff-dc221c544e8594d295396c6fdc78f1bf

CI should catch this (similar to bad colors)

**Comment by pjlao307** [comment]
Right, and there was another case where the images were way too big.
https://github.com/commaai/comma10k/pull/180

**Comment by tracminhvu** [comment]
I guess the check will making sure the size is 1164x874 px, and dpi=72?

**Comment by nelsonjchen** [comment]
@tracminhvu Size of course, but I'm not sure if a DPI check is important.
