### ISSUE TITLE
Why not make labeling simpler?

### ISSUE THREAD

**Issue by TKassis** [commaai/comma10k#2624]
I'm so exciting about Comma's OpenPilot project, it's great to see a company democratizing technologies that many covet but can't come close to affording (Tesla AutoPilot!). I'm curious though why a simple labeling project is designed in such a convoluted manner. Why not use a platform like LabelBox or Sagemaker Groundtruth and share the labeling link with the Comma community? This streamlines the labeling process, introduces redundancies in labeling and makes everyone's life easier. I would love to help out with labeling but there are so many tedious steps with getting up and running that I just don't want to deal with.

**Comment by dorkmo** [comment]
most everyone labeling is using photoshop. Early days they had a web based labeler, but the output was not great. Labelbox seems a bit opaque on pricing for large data sets, probably not worth entering a contract while not knowing quality of end product.

**Comment by pjlao307** [comment]
Most people use image-labeler (linked in the README).  There's no steps to setup, it's an online tool.

**Comment by TKassis** [comment]
It just seems very convoluted, having to fork the repo, create a new branch, submit a pull request, individual validation (as opposed to building labeling redundancy)... I really feel this project would have be been completed a lot sooner with a more streamlined labeling process :-)
