### ISSUE TITLE
Raw videos out of which the pngs were extracted

### ISSUE THREAD

**Issue by MalteEbner** [commaai/comma10k#2763]
For using self-supervised learning, it would be great to have unlabeled data, e.g. raw videos, additional to the 10k labeled frames.
Are the raw videos you chose the 10k frames from somewhere available? 

The videos must not be limited to the ones from which at least 1 frame was extracted, they may also from other drives.

**Comment by doktorsleepelss** [comment]
Video isn't available for the pngs from the comma10k set, but comma has the comma2k19 datset with 33 hours of video. 
https://github.com/commaai/comma2k19

**Comment by MalteEbner** [comment]
Thank you @doktorsleepelss !
