### ISSUE TITLE
[410-420] PvE farming no RDM

### ISSUE THREAD

**Issue by git6578** [commaai/comma10k#298]

**Comment by pjlao307** [comment]
Check the spreadsheet: https://docs.google.com/spreadsheets/d/1T1kQx-d6iupRlC4ErCyDO9LM59N9cQTSCeXYDSHM3C8

410-416 have already been claimed and 420 is already done.

**Comment by git6578** [comment]
I pulled 410-415, first time i hear from this list unfortunately. ty

**Comment by git6578** [comment]
should i just finish this batch or abort?

**Comment by pjlao307** [comment]
abort
