### ISSUE TITLE
0090 - russbb02

### ISSUE THREAD

**Issue by russbb02** [commaai/comma10k#324]
first attempt

**Comment by pjlao307** [comment]
90 is already being worked on by someone.

Please check the other issues (opened and closed) or the spreadsheet: https://docs.google.com/spreadsheets/d/1T1kQx-d6iupRlC4ErCyDO9LM59N9cQTSCeXYDSHM3C8

**Comment by pjlao307** [comment]
Nvm, looks like they closed it without submitting a PR

**Comment by Kogepang** [comment]
90 Kogepang
i fixed and make PR now.

**Comment by pjlao307** [comment]
https://github.com/commaai/comma10k/pull/507
