### ISSUE TITLE
alexodonnell12 (97- 107)

### ISSUE THREAD

**Issue by alexodonnell12** [commaai/comma10k#40]
97 to 107 in progress

**Comment by pjlao307** [comment]
99,100 have already been submitted. See:
https://github.com/commaai/comma10k/pull/13

**Comment by pjlao307** [comment]
Also 101-105: https://github.com/commaai/comma10k/pull/30

**Comment by jason-h-simplifi** [comment]
106 and 107 got merged.

**Comment by pjlao307** [comment]
So only 97, 98 are good to work on.

**Comment by Hubblesphere** [comment]
97 and 98 are done.
