### ISSUE TITLE
ScottieAdair (150 - 189)

### ISSUE THREAD

**Issue by scottadair** [commaai/comma10k#42]

**Comment by scottadair** [comment]
150 - 160 are done and merged

**Comment by scottadair** [comment]
161 - 165 submitted, pending merge

**Comment by scottadair** [comment]
172 to 179 are done

**Comment by pjlao307** [comment]
Are you doing all of them in the same PR?  If so I'll wait till all of them are in so I don't lose track of what I'm looking at.

**Comment by pjlao307** [comment]
Nvm, I'll go ahead and review this PR

**Comment by scottadair** [comment]
Yeah just wanted to block off a chunk. Can't create smaller sets if it's easier
