### ISSUE TITLE
CommaPencil bugs + 1 feature request

### ISSUE THREAD

**Issue by pjlao307** [commaai/comma10k#85]
Tested this on windows 10 and found a few bugs:

**Bugs:**

1. When zooming in and the image is bigger than the viewable area you can't scroll horizontally, only vertically so you can't edit anything that's cut off on the left side of the image.
2. The generated image suffers from the BAD COLORS problem because the edges are anti-aliased.

**Feature request:**

It would make tagging easier if it also had a polyfill function (photoshop has this) where you can click points in the polygon and then it fills the color.  This makes tagging more precise than having to be very accurate with the mouse (unless you have a wacom tablet to do this with).

**Comment by geohot** [comment]
It's probably better to get the commacoloring tool working again.

https://github.com//commaai/commacoloring

**Comment by pjlao307** [comment]
This may be a better option:
https://erikbernheim.github.io/img-labeler/
